// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHNJEABWldiVfsF7qEEtdHTbKvnD_WUg',
    appId: '1:315952758909:android:f312845826aa34c12e7114',
    messagingSenderId: '315952758909',
    projectId: 'signuploginfirebase-ed555',
    storageBucket: 'signuploginfirebase-ed555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxa35wiUEOBwHoUZhfEWyS3cfUzJlz3nk',
    appId: '1:315952758909:ios:3552502a4d7dc0642e7114',
    messagingSenderId: '315952758909',
    projectId: 'signuploginfirebase-ed555',
    storageBucket: 'signuploginfirebase-ed555.firebasestorage.app',
    iosBundleId: 'com.example.signandloginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxa35wiUEOBwHoUZhfEWyS3cfUzJlz3nk',
    appId: '1:315952758909:ios:3552502a4d7dc0642e7114',
    messagingSenderId: '315952758909',
    projectId: 'signuploginfirebase-ed555',
    storageBucket: 'signuploginfirebase-ed555.firebasestorage.app',
    iosBundleId: 'com.example.signandloginFirebase',
  );
}
